### ISSUE TITLE
Add newsletter signup form back!

### ISSUE THREAD

**Issue by nassdonald** [cosmos/cosmos.network#122]
In the process of redesigning the footer, we somehow forgot to add the signup form for the newsletters. 😳 

Let's use the existing component we have and then update the design to incorporate better with the footer. Also, as requested, let's find a better way to incentivize signups by promoting somewhere else on the homepage too.

## Todo
- [x] Display existing newsletter signup form component above footers - @lovincyrus 
- [x] Redesign footer to include newsletter signup form - [Asana task](https://app.asana.com/0/1188752297235382/1200178416908675/f)
- [x] Promote newsletter signup CTA somewhere on the homepage - [Asana task](https://app.asana.com/0/1188752297235382/1200178416908677/f)

**Comment by miguel-tendermint** [comment]
@lovincyrus I've put together a version of the newsletter sign-up component with the new visuals [here](https://www.figma.com/file/jwsszv5yFMnIj12Vry8E75/cosmos.network-2021?node-id=2997%3A22714)! I think all states were considered, but let me know if anything's missing! Here's what it looks like in the wild!
<img width="844" alt="Screenshot 2021-04-22 at 15 00 07" src="https://user-images.githubusercontent.com/76948640/115727363-6ffba600-a37b-11eb-96af-1b4a2811cdaa.png">
