### ISSUE TITLE
Starport page refinements

### ISSUE THREAD

**Issue by nassdonald** [cosmos/cosmos.network#84]
- [ ] Fix alignment and sizing of hero graphics - see #64 
- [ ] @miguel-tendermint to create a custom placeholder image for Starport video.
- [ ] @lovincyrus to enable volume and time scrubber controls.
- [ ] "The toolkit of leading blockchains" title column span should be the include all remaining columns on the row, and a max-width of `10em`.
- [ ] @miguel-tendermint to provide consistent logo canvas sizes, for `.logos-list`.
- [ ] @lovincyrus to reduce gap between logos to `var(--grid-gap-x)` and add `justify-items: center` to the grid container for the logos.
- [ ] @lovincyrus to refactor the layout of the stats and intro bottom section to use the 12 col grid and maximize the available space responsively.
- [ ] Convert terminal and browser windows to CSS/HTML - see #64 
- [ ] @lovincyrus to add `.tm-measure-narrower` to `.col` in each section.
- [ ] @lovincyrus to remove hover-raise on final build CTA panel.
- [ ] @lovincyrus to add dyson sphere graphics to final CTA panel.
- [ ] @lovincyrus to replace ATOM coins with reusable coins in funding CTA panel - as per #64 
- [ ] Developer chat panel CTA should have an external link icon.

**Comment by miguel-tendermint** [comment]
@lovincyrus Tweaked the play button and added a new thumbnail, will connect with you shortly regarding the canvas size for the logo list

**Comment by miguel-tendermint** [comment]
@lovincyrus logo-list now has a bounding box with the same size for every logo, updated on figma!
